##################################################
# Gustavo Kennedy Renkel - Ansible Playbook de configuração inicial para Ubuntu 20.04 
##################################################
---
- hosts: localhost
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Instala Pré-requisitos
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]
      
    - name: Atualiza repositórios e cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Atualiza pacotes APT
      apt: upgrade=dist force_apt_get=yes

    - name: Instala pacote LEMP
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'nginx', 'mysql-server', 'python3-pymysql', 'php-fpm', 'php-mysql' ]
      
     - name: Instala NVM
       shell: >
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
       args:
          creates: "/root/.nvm/nvm.sh"

      - name: Instala Versões do Node
        shell: ". /root/.bashrc && nvm install {{item}}"
        with_items: 
          - 'v10.24.1'
          - 'v16.17.0'
          - '--lts'
          - 'node'
    
# Configuração Ansible para Ubuntu 20.04 - Nginx e Let's Encrypt

    - name: Instala LetsEncrypt
      apt: name=letsencrypt state=latest
      
    - name: Cria diretório LetsEncrypt
      file: name=/var/www/letsencrypt state=directory
      
    - name: Gera arquivo de configuração do Nginx
      template:
        src: "files/nginx.conf.j2"
        dest: "/etc/nginx/sites-available/{{ dominio }}.conf"
        
    - name: Cria diretório dominio HTML
      file: name=/var/www/html/{{ dominio }} state=directory
        
    - name: Gera arquivo de Index OC
      template:
        src: "files/index.nginx-debian.html.j2"
        dest: "/var/www/html/{{ dominio }}/index.nginx-debian.html"
        
    - name: Copia arquivo de configuração do Available para Enabled
      file:
        src: "/etc/nginx/sites-available/{{ dominio }}.conf"
        dest: "/etc/nginx/sites-enabled/{{ dominio }}.conf"
        state: link
      notify: Recarrega Nginx
      
#    - name: Cria Certificado LetsEncrypt
#      shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ dominio }} -d www.{{ dominio }}
#      args:
#        creates: /etc/letsencrypt/live/{{ dominio }}
       
    - name: Adiciona Cronjob para renovação dos certificado LetsEncrypt
      cron:
        name: letsencrypt_renewal
        special_time: weekly
        job: letsencrypt --renew certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ dominio }} && service nginx reload

    - name: Remove sites "default" do Nginx
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent
      notify: Reinicia Nginx

# Configuração Ansible para Ubuntu 20.04 - MySQL

    - name: Ajusta permissões no MySQL my.cnf
      become: yes
      become_user: root
      lineinfile:
        path: /etc/mysql/my.cnf
        line: "[mysqld] skip-grant-tables"
        state: present
        backup: yes

    - name: Cria banco de dados
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ db_nome }}"
        state: present 

    - name: Instala PHPMYADMIN - DBConfig
      debconf: name=phpmyadmin question='phpmyadmin/dbconfig-install' value='true' vtype='boolean'

    - name: Instala PHPMYADMIN - Confirma senha
      debconf: name=phpmyadmin question='phpmyadmin/app-password-confirm' value='root' vtype='password'

    - name: Instala PHPMYADMIN - Altera senha admin
      debconf: name=phpmyadmin question='phpmyadmin/mysql/admin-pass' value='root' vtype='password'

    - name: Instala PHPMYADMIN - Confirma senha app
      debconf: name=phpmyadmin question='phpmyadmin/mysql/app-pass' value='root' vtype='password'

    - name: Instala PHPMYADMIN - reconfigura webserver
      debconf: name=phpmyadmin question='phpmyadmin/reconfigure-webserver' value='' vtype='multiselect'

    - name: Instala PHPMYADMIN
      apt: pkg=phpmyadmin state=present

    - name: Configura pastas para webserver
      file: path=/var/www/phpmyadmin src=/usr/share/phpmyadmin state=link

# Configuração Ansible para Ubuntu 20.04 - PHP

    - name: Define PHP Info Page no Nginx
      template:
        src: "files/info.php.j2"
        dest: "/var/www/html/{{ dominio }}/info.php"

  handlers:
    - name: Recarrega Nginx
      service:
        name: nginx
        state: reloaded

    - name: Reinicia Nginx
      service:
        name: nginx
        state: restarted

    - name: Reinicia MySQL
      service:
        name: mysql
        state: restarted
